---
apiVersion: v1
kind: ConfigMap
metadata:
  name: lockdown-network-policy-cm
  namespace: projectsveltos
  annotations:
    projectsveltos.io/instantiate: ok
data:
  networkpolicy.yaml: |
    apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: {{ .Resource.metadata.name }}-lockdown-network-policy
      namespace: {{ .Resource.metadata.name }}
    spec:
      podSelector: {}
      policyTypes:
      - Ingress
  