---
apiVersion: lib.projectsveltos.io/v1beta1
kind: EventSource
metadata:
  name: private-namespace-event-source
  namespace: projectsveltos
spec:
  collectResources: true
  resourceSelectors:
  - group: ""
    version: "v1"
    kind: "Namespace"
    evaluate: |
      function evaluate()
        hs = {}
        hs.matching = false
        hs.message = ""
        if obj.metadata.labels ~= nil then
          for key, value in pairs(obj.metadata.labels) do
            if key == "access" then
              if value == "private" then
                hs.matching = true
              end
            end
          end
        end
        return hs
      end