---
apiVersion: lib.projectsveltos.io/v1beta1
kind: EventTrigger
metadata:
  name: service-account-token-trigger
  namespace: projectsveltos
spec:
  sourceClusterSelector:
    matchLabels:
      managedBy: sveltos
  eventSourceName: service-account-event-source
  oneForEvent: true
  policyRefs:
  - name: bot-sa-token-cm
    namespace: projectsveltos
    kind: ConfigMap
