---
apiVersion: lib.projectsveltos.io/v1beta1
kind: EventTrigger
metadata:
  name: private-namespace-network-policy-trigger
  namespace: projectsveltos
spec:
  sourceClusterSelector:
    matchLabels:
      managedBy: sveltos
  eventSourceName: private-namespace-event-source
  oneForEvent: true
  policyRefs:
  - name: lockdown-network-policy-cm
    namespace: projectsveltos
    kind: ConfigMap
